# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: meghribe <meghribe@student.42barcelon      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/08/10 16:18:35 by meghribe          #+#    #+#              #
#    Updated: 2025/08/11 22:41:43 by meghribe         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:

.PHONY: clean
clean:

.PHONY: fclean
fclean:

.PHONY: re
re: fclean all
